# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: caa85c7ebf6f2d89a0c68846e42d89d34a9349b9fac921a5c0b851705a56816d2b6e4f90f59f7520114b73672678e1f5ef7e31054953e857f51552a0d18aff6b

test:
  secret_key_base: 47f51d1552093c9836262787e795e4e62eb103b67ca072dd0f994d20e1be259d1b65bc926c7e2b59683ec49fae90d723910a3681f2b8ee0e50c10264bd054493

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
